addons:
  sauce_connect: true
  chrome: stable
language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng test --watch=false --browsers=ChromeHeadless
- npm run e2e
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist/ng-my-presentation
  on:
    branch: master
env:
  global:
  - secure: Z9P9Z8FpbOaOuA3xCALQIVdPJWOEJsVlLXbzMjo/DSQIfKy73g0VNHIxsSAcgbS7ISBm4BhRjJjb+JnR8JQeqoiQDahIcmpLt02ArCG85ezK59K5rW/Z1SZHzdOuO7LAPxfx4sqNTnRi59FrYN762ooxXHAdbD18Pqin+oZduvGSbgLb7aD/5Ilo8pc+hj1QueLSr1qk8ogHgwr/4wggoWi9P+FiOZeY89ygHhPfHQXNtvxwc00N9pYj+r2wzzHixQAnHOG6t3EtiV7FdKcsg9pKn202ugqyeL8gg3CsIW4i5CoKlm3ink2xWBal0JQOxsAYyDk26swxGNhP3RkVtvWbQDTwGourwt1HOpGs4KGJWNv3hS+RzgMAAW9K3U5b2tZh9493AMiMT/KWs5RRFiUJ/wbkaO1fsdq0cOFmluNY9wCApnfcF3ks1t3KcPt0tZZOrexFEGBor7+N76/OV0iaplVlLhNxoHuUQOgqoiJU9i/f/OlAUpekFcyvkDTBrMVjnikBKmEQblJ2aOouvCxjljeAEMvuYMXLtdQAatBkKOcDBiUe9fDmUFIqHqCcPl/uC4ioL1OMddoNCqJkFfxwRI+UKV3kMUBfeCI82Al3gEUFCce29FasMO1t0ZqvvGXvPkG1bVvFxAU8ORByuXbIGl64UNQ25mA9+lXjy48=
  - secure: ll6sxGljLDXLZOuO9EGKGOIPCw9L+a7sQhMzS5gqcYeMYtCukt+/Yyq9/+0Lszo1VaMDLFxHuLU/CZtLGVD8OzQiNZte/LQ1SuYBHSghnNVC+w9INPhxg1YwSBxfNZl++nSuqKEr33a4OvQ9GGTd6x5coWp5DoIAwQLfGjvxJK+UaxZNvrhW3LNpvT4thUqxAcJyzVoBcF8sOyQ51z8uU4TWzM6mxRmO3dfYS4mF7SsjTZnsnuKgX+0v25h06+AOHqVtOBAw786mFHuqDLP2h4nrYqhYIfcA3Jx1UGUuUP8HayDCJWIx54EsuHRBckKpP9Egg18IecNh7u4SMGNID2SKM/GnH+lBHO4F6OzaQpgqGDC489uB/4C8V/uhcZOJhMoQo0G+zTdewiyb4E99PCHA83f24UDZLSTTsLuf7eexdiMziWJC9XKR7dLtECjegts771Y77Yykn6XhRpDh84OBhzUDJtq90zYlfIg9C11BCY2+6eracZrtDcXCy2r+WJZWEqhbVWR/EoZnxNNZPw5GPStAbajuyWS8Wd23wxeKoSy35wpzfpg8V8E0GTqD/C8ZKvT7U6GPBrGKZwelSGVM+BL80XlQtg7UpTn7CQoc8YyD+1fxS2CevarkXGxbLBQAdf0BiTuqSiwTdigsSSMR1urGty4lltrdtrQoOCQ=
