language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://sujono91.github.io/ng-my-presentation/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-my-presentation
  on:
    branch: master
